name: CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  codespell:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.x

      - name: Install codespell
        run: pip install codespell

      - name: Run codespell
        run: codespell *

  autoflake:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.x

      - name: Install autoflake
        run: pip install autoflake

      - name: Run autoflake
        run: autoflake .

  test:
    runs-on: ${{ matrix.os }}
    env:
      PYTEST_ADDOPTS: "--color=yes"
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python: ["3.8", "3.9", "3.10", "3.11", "3.12"]

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Setup Python ${{ matrix.python }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}

      - name: Install pak
        run: pip install .[tests,docs]

      - name: Run tests (checking code coverage)
        run: pytest

      - name: Upload code coverage
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Run doctests in rst files
        run: make -C docs doctest
