name: CI
on: [push, pull_request]


jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python: [3.7, 3.8, 3.9]


    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Setup Python ${{ matrix.python }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}

      - name: Install pak.py
        run: pip install .

      - name: Run tests
        run: pytest --color=yes

      - name: Run doctests
        run: |
          cd docs
          pip install -r requirements.txt
          make doctest
