name: CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  codespell:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install codespell
        run: pip install codespell

      - name: Run codespell
        run: codespell *

  test:
    runs-on: ${{ matrix.os }}
    env:
      PYTEST_ADDOPTS: "--color=yes"
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python: ["3.7", "3.8", "3.9", "3.10"]


    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Setup Python ${{ matrix.python }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}

      - name: Install pytest
        run: pip install pytest

      - name: Install pak.py
        run: |
          pip install -r requirements.txt
          pip install .

      - name: Run tests
        run: pytest

      - name: Run doctests in docstrings
        run: pytest --doctest-modules pak

      - name: Run doctests in rst files
        run: |
          cd docs
          pip install -r requirements.txt
          make doctest
